config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kit.urls')),
]

kit/urls.py
from django.urls import path
from .views import QuestionsPageView, IndexView, ResultsView

app_name = 'kit'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('questions/', QuestionsPageView.as_view(), name='questions'),
    path('results/', ResultsView.as_view(), name='results'),
]

kit/models.py
from django.db import models
from users.models import User


class Category(models.Model):
    """ Each question belongs to a specific category for example, desktop computers, mobile phones etc"""
    name = models.CharField(max_length=250, blank=False, null=False, unique=True)

    def __str__(self):
        return self.name


class Answer(models.Model):
    """An answer is a choice in a question. An answer can be correct or wrong"""
    answer = models.CharField(blank=False, null=False, unique=True, max_length=50)
    weight = models.IntegerField(default=5, verbose_name='marks')

    def __str__(self):
        return self.answer


class Question(models.Model):
    """This model defines a question,its choices, the category, and the correct answer."""
    question = models.CharField(max_length=250, blank=False, null=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='questions')
    choices = models.ManyToManyField(Answer, blank=False, related_name='questions_choices')
    correct_answer = models.ForeignKey(Answer, on_delete=models.DO_NOTHING, related_name='questions_correct_answer',
                                       null=True, blank=False,
                                       )

    def __str__(self):
        return self.question

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

kit/views.py
from django.views.generic import TemplateView
from django.views import View
from .models import Question, Category, Answer
from django.shortcuts import render, redirect
from django.contrib import messages


class IndexView(TemplateView):
    template_name = 'index.html'


class QuestionsPageView(View):
    template = 'questions.html'

    def get(self, request, *args, **kwargs):
        context = {
            'categories': Category.objects.all()
        }
        return render(request, self.template, context)

    def post(self, request, *args, **kwargs):
        data = dict(request.POST.copy())
        data.pop('csrfmiddlewaretoken')

        request.session['marks_per_category'] = calculate_marks_per_category(data=data)

        return redirect('kit:results')


class ResultsView(View):
    template = 'results.html'

    def get(self, request):
        marks_per_category = request.session.get('marks_per_category')

        context = {
            'marks_per_category': marks_per_category,
            'total_marks_scored': calculate_total_marks_scored(marks_per_category),
            'test_total_marks': calculate_test_total_marks(),
        }

        return render(request, self.template, context)


def calculate_marks_per_category(data) -> dict:
    """Calculate the marks per category."""

    categories = Category.objects.all()
    marks_per_category = {category.name: 0 for category in categories}

    for key in data:
        question = Question.objects.get(id=int(key))
        user_answer = Answer.objects.get(id=int(data[key][0]))

        if user_answer.answer == str(question.correct_answer):
            marks_per_category[str(question.category)] += user_answer.weight
        else:
            marks_per_category[str(question.category)] += 0

    return marks_per_category


def calculate_total_marks_scored(marks_per_category: dict) -> int:
    """Calculate the total marks the user scored."""

    total_marks = 0

    for marks in marks_per_category.values():
        total_marks += marks
    return total_marks


def calculate_test_total_marks() -> int:
    """Calculate the total marks for the test."""

    questions = Question.objects.all()
    total_marks = 0

    for question in questions:
        total_marks += int(question.correct_answer.weight)
    return total_marks

kit/templates/index.html
{% extends 'kit_base.html' %}
{% load static %}
{% block title %} Digital Literacy Self Assessment Kit {% endblock %}
{% block content %}
    <div class ="container">
          <div class="row  mt-5 justify-content-center ">
              <div class="col-sm-6 bg-transparent border rounded border-dark">
                  <p>
                        Digital literacy has become an essential skill in the life of the average Kenyan.
                        This <b>Digital Literacy Assessment Kit </b> is designed to assess your proficiency in the
                        most ubiquitous digital platforms. These platforms are:
                        <ol>
                            <li> Desktop Computers </li>
                            <li> Mobile phones</li>
                            <li> Mobile banking </li>
                            <li> Social Media </li>
                        </ol>

                  <div class="col text-center mb-3 ">
                    <a href="{% url 'kit:questions' %}"  type="button" class="btn btn-outline-dark">Get Started </a>
                  </div>
               </div>
          </div>
    </div>
{% endblock %}

kit/templates/kit_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script type="text/javascript" src= {% static 'js/bootstrap.bundle.min.js' %}></script>
    {% block style %}{% endblock %}
</head>
<body>
    {% block content%}{% endblock %}
</body>
</html>

kit/templates/questions.html
{%extends 'kit_base.html'%}
{%load static%}
{%block title%}Assessment Test{%endblock%}
{% block style %}
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            background-color: #f1f1f1;
        }

        #regForm {
            background-color: #ffffff;
            margin: 100px auto;
            padding: 40px;
            width: 70%;
            min-width: 300px;
        }

        h1 {
            text-align: center;
        }


        /* Hide all steps by default: */
        .tab {
            display: none;
        }

        /* Make circles that indicate the steps of the form: */
        .step {
            height: 15px;
            width: 15px;
            margin: 0 2px;
            background-color: #bbbbbb;
            border: none;
            border-radius: 50%;
            display: inline-block;
            opacity: 0.5;
        }

        .step.active {
            opacity: 1;
        }

        /* Mark the steps that are finished and valid: */
        .step.finish {
            background-color: #4CAF50;
        }
    </style>
{%endblock%}
{%block content%}

    <form id="regForm" action="{% url 'kit:questions' %}" method="post">
        {% csrf_token %}
        {% for category in categories %}
            <div class="tab">
                <h1> {{ category }}</h1>
                <ol>
                    {% for question in category.questions.all %}
                        <li>{{ question.question }}</li>
                        {% for choice in question.choices.all %}
                            <input required id="{{ question.id }}{{ choice.id }}" type="radio" value="{{ choice.id }}"
                                   name="{{ question.id }}">
                            <label for="{{ question.id }}{{ choice.id }}">{{ choice }}</label>
                            <br>
                        {% endfor %}
                    {% endfor %}
                </ol>
            </div>
        {% endfor %}

        <div style="float:right;">
            <button type="button" class="btn btn-outline-secondary" id="prevBtn" onclick="nextPrev(-1)">Previous</button>
            <button type="button" class="btn btn-outline-success" id="nextBtn" onclick="nextPrev(1)">Next</button>
        </div>
        <!-- Circles which indicates the steps of the form: -->
        <div style="text-align:center;margin-top:40px;">
            <span class="step"></span>
            <span class="step"></span>
            <span class="step"></span>
            <span class="step"></span>
        </div>
    </form>

    <script>
        var currentTab = 0; // Current tab is set to be the first tab (0)
        showTab(currentTab); // Display the current tab

        function showTab(n) {
            // This function will display the specified tab of the form...
            var x = document.getElementsByClassName("tab");
            x[n].style.display = "block";
            //... and fix the Previous/Next buttons:
            if (n == 0) {
                document.getElementById("prevBtn").style.display = "none";
            } else {
                document.getElementById("prevBtn").style.display = "inline";
            }
            if (n == (x.length - 1)) {
                document.getElementById("nextBtn").innerHTML = "Submit";
            } else {
                document.getElementById("nextBtn").innerHTML = "Next";
            }
            //... and run a function that will display the correct step indicator:
            fixStepIndicator(n)
        }

        function nextPrev(n) {
            // This function will figure out which tab to display
            var x = document.getElementsByClassName("tab");
            // Exit the function if any field in the current tab is invalid:
            if (n == 1 && !validateForm()) return false;
            // Hide the current tab:
            x[currentTab].style.display = "none";
            // Increase or decrease the current tab by 1:
            currentTab = currentTab + n;
            // if you have reached the end of the form...
            if (currentTab >= x.length) {
                // ... the form gets submitted:
                document.getElementById("regForm").submit();
                return false;
            }
            // Otherwise, display the correct tab:
            showTab(currentTab);
        }

        function validateForm() {
            // This function deals with validation of the form fields
            var x, y, i, valid = true;
            x = document.getElementsByClassName("tab");
            y = x[currentTab].getElementsByTagName("input");
            // A loop that checks every input field in the current tab:
            for (i = 0; i < y.length; i++) {
                // If a field is empty...
                if (y[i].value == "") {
                    // add an "invalid" class to the field:
                    y[i].className += " invalid";
                    // and set the current valid status to false
                    valid = false;
                }
            }
            // If the valid status is true, mark the step as finished and valid:
            if (valid) {
                document.getElementsByClassName("step")[currentTab].className += " finish";
            }
            return valid; // return the valid status
        }

        function fixStepIndicator(n) {
            // This function removes the "active" class of all steps...
            var i, x = document.getElementsByClassName("step");
            for (i = 0; i < x.length; i++) {
                x[i].className = x[i].className.replace(" active", "");
            }
            //... and adds the "active" class on the current step:
            x[n].className += " active";
        }
    </script>
{%endblock%}
</html>

kit/templates/results.html
{%extends 'kit_base.html'%}
{%load static%}
{%block title%}Assessment Test{%endblock%}
{% block style %}
    <style>
        * {
            box-sizing: border-box;}

        body {
            background-color: #f1f1f1;}

        h3,h5 {
            text-align: center;}

        .results{
            background-color: #ffffff;
            margin: 100px auto;
            padding: 40px;
            width: 50%;
            max-width: 500px;
        }

    </style>
{%endblock%}
{%block content%}

    <div class="results">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th scope="col">Category</th>
                    <th scope="col">Marks</th>
                <tr>
            </thead>
            <tbody>
                {% for key, value  in marks_per_category.items %}
                    <tr>
                        <td> {{ key }}</td>
                        <td>{{ value }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <th scope="row"> Total Marks </th>
                    <td>{{ total_marks_scored }}/{{ test_total_marks }}</td>
                </tr>
            </tbody>
        </table>
    </div>

{% endblock %}